
spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: SensorRequestHandlerApplication1
          uri: http://localhost:8081
          predicates:
            - Path=/sensors/**
          filters:
            - PrefixPath=/api

        - id: SensorRequestHandlerApplication2
          uri: http://localhost:8082
          predicates:
            - Path=/sensors/**
          filters:
            - PrefixPath=/api

